#!/bin/bash
#
# Copyright 2016-2018 the Bayou Authors (Dan Bornstein et alia).
# Licensed AS IS and WITHOUT WARRANTY under the Apache License,
# Version 2.0. Details: <http://www.apache.org/licenses/LICENSE-2.0>
#
# Starts the product, building it first if sitting in a clean directory. See
# `--help` for more info.
#

# Set `progName` to the program name, `progDir` to its directory, and `baseDir`
# to `progDir`'s directory. Follows symlinks.
function init-prog {
    local newp p="$0"

    while newp="$(readlink "$p")"; do
    [[ ${newp} =~ ^/ ]] && p="${newp}" || p="$(dirname "$p")/${newp}"
    done

    progName="${p##*/}"
    progDir="$(cd "$(dirname "$p")"; /bin/pwd -P)"
    baseDir="$(cd "${progDir}/.."; /bin/pwd -P)"
}
init-prog


#
# Helper functions
#

# Helper for `check-environment-dependencies` which validates one dependency.
function check-dependency {
    local name="$1"
    local versionCmd="$2"
    local match="$3"

    # Extract just the command name, and verify that it exists at all.

    local cmdName=''
    if [[ ${versionCmd} =~ ^([^ ]+) ]]; then
        cmdName="${BASH_REMATCH[1]}"
    else
        # **Note:* This indicates a bug in this script, not a problem with the
        # environment.
        echo "Could not determine commmand name for ${name}." 1>&2
        exit 1
    fi

    if ! which "${cmdName}" >/dev/null 2>&1; then
        echo "Missing required command for ${name}: ${cmdName}" 1>&2
        exit 1
    fi

    local version="$(${versionCmd} 2>&1)"
    if ! grep -q -e "${match}" <<< "${version}"; then
        echo "Unsupported version of ${name}: ${version}" 1>&2
        exit 1
    fi
}

# Checks the versions of our various expected-installed dependencies.
function check-environment-dependencies {
    check-dependency 'Node' 'node --version' '^v[89]\.'
}


#
# Main script
#

check-environment-dependencies
cd "${baseDir}/server"
exec node node_modules/.bin/bayou-server --prog-name="${progName}" "$@"
