// Copyright 2016-2019 the Bayou Authors (Dan Bornstein et alia).
// Licensed AS IS and WITHOUT WARRANTY under the Apache License,
// Version 2.0. Details: <http://www.apache.org/licenses/LICENSE-2.0>

import { BodyDelta } from '@bayou/doc-common';
import { ChainedEvent, EventSource } from '@bayou/promise-util';
import { TString } from '@bayou/typecheck';
import { Errors, Functor, ObjectUtil, UtilityClass } from '@bayou/util-common';

/**
 * Utility class for wrangling the events generated by Quill.
 */
export class QuillEvents extends UtilityClass {
  /** {String} Event source for the API. */
  static get SOURCE_api() {
    return 'api';
  }

  /**
   * {String} Event source for activity which should be "ignored" (for some
   * sense of the term).
   */
  static get SOURCE_silent() {
    return 'silent';
  }

  /** {String} Event source for user (human) activity. */
  static get SOURCE_user() {
    return 'user';
  }

  /**
   * {Functor} Event payload representing an empty text change caused by the
   * `api` source.
   */
  static get EMPTY_TEXT_CHANGE_PAYLOAD() {
    return new Functor(
      QuillEvents.TYPE_textChange, BodyDelta.EMPTY, BodyDelta.EMPTY, QuillEvents.SOURCE_api);
  }

  /**
   * {String} Event type/name for editor change events. **Note:** The string
   * value of this variable is dictated by Quill and so violates the default
   * local conventions.
   */
  static get TYPE_editorChange() {
    return 'editor-change';
  }

  /**
   * {String} Event type/name for selection change events. **Note:** The string
   * value of this variable is dictated by Quill and so violates the default
   * local conventions.
   */
  static get TYPE_selectionChange() {
    return 'selection-change';
  }

  /**
   * {String} Event type/name for text change events. **Note:** The string value
   * of this variable is dictated by Quill and so violates the default local
   * conventions.
   */
  static get TYPE_textChange() {
    return 'text-change';
  }

  /**
   * Emits a `ChainedEvent` on the given `EventSource`, based on the payload
   * of a Quill event callback. This "fixes" the payload (via
   * {@link #fixPayload}) so that the various values adhere to the
   * `@bayou/doc-client` contract.
   *
   * @param {EventSource} source Source to emit from.
   * @param {Functor} payload Original Quill event payload, where the functor
   *   name is the name of the original event, and the functor arguments are the
   *   arguments as originally passed to the event handler callback.
   * @returns {ChainedEvent} The emitted event.
   */
  static emitQuillPayload(source, payload) {
    EventSource.check(source);

    return source.emit(QuillEvents.fixPayload(payload));
  }

  /**
   * "Fixes" and validates the given event payload. The fixing takes into
   * account the fact that Quill will produce events with non-immutable data.
   *
   * @param {Functor} payload Event payload in question.
   * @returns {Functor} Fixed payload.
   */
  static fixPayload(payload) {
    Functor.check(payload);
    const name = payload.name;

    switch (name) {
      case QuillEvents.TYPE_textChange: {
        const [delta, oldContents, source] = payload.args;
        return new Functor(name,
          BodyDelta.fromQuillForm(delta),
          BodyDelta.fromQuillForm(oldContents),
          TString.check(source));
      }

      case QuillEvents.TYPE_selectionChange: {
        const [range, oldRange, source] = payload.args;
        return new Functor(name,
          QuillEvents._checkAndFreezeRange(range),
          QuillEvents._checkAndFreezeRange(oldRange),
          TString.check(source));
      }

      default: {
        throw Errors.badValue(payload, 'Quill event payload');
      }
    }
  }

  /**
   * Gets the payload of the given event or event payload, as an object with
   * named properties.
   *
   * @param {ChainedEvent|Functor} eventOrPayload Event or event payload in
   *   question.
   * @returns {object} The properties of `event`'s payload, in convenient named
   *   form.
   */
  static propsOf(eventOrPayload) {
    const payload = (eventOrPayload instanceof Functor)
      ? eventOrPayload
      : ChainedEvent.check(eventOrPayload).payload;
    const name = payload.name;

    switch (name) {
      case QuillEvents.TYPE_textChange: {
        const [delta, oldContents, source] = payload.args;
        return { name, delta, oldContents, source };
      }

      case QuillEvents.TYPE_selectionChange: {
        const [range, oldRange, source] = payload.args;
        return { name, range, oldRange, source };
      }

      default: {
        throw Errors.badValue(payload, 'Quill event payload');
      }
    }
  }

  /**
   * Validates a "range" object as provided by Quill. This accepts `null` as
   * a valid value. If the range is valid and non-`null`, freezes it.
   *
   * @param {*} range The (alleged) range.
   * @returns {object} The validated frozen range.
   */
  static _checkAndFreezeRange(range) {
    return (range === null)
      ? null
      : ObjectUtil.extract(range, ['index', 'length']);
  }
}
