#!/bin/bash
#
# Copyright 2016-2018 the Bayou Authors (Dan Bornstein et alia).
# Licensed AS IS and WITHOUT WARRANTY under the Apache License,
# Version 2.0. Details: <http://www.apache.org/licenses/LICENSE-2.0>
#
# Converts the module sources in `out` into a form which is appropriate to hand
# off to `npm publish`, and optionally also actually publishes them.
#

# Set `progName` to the program name, `progDir` to its directory, and `baseDir`
# to `progDir`'s directory. Follows symlinks.
function init-prog {
    local newp p="$0"

    while newp="$(readlink "$p")"; do
        [[ ${newp} =~ ^/ ]] && p="${newp}" || p="$(dirname "$p")/${newp}"
    done

    progName="${p##*/}"
    progDir="$(cd "$(dirname "$p")"; /bin/pwd -P)"
    baseDir="$(cd "${progDir}/.."; /bin/pwd -P)"
}
init-prog

# Move `baseDir` and `prodDir` up one layer (not done above because the above is
# boilerplate).
progDir="${baseDir}"
baseDir="$(cd "${baseDir}/.."; /bin/pwd -P)"

# Pull in the build system helper library.
. "${progDir}/lib/include-build.sh"


#
# Argument parsing
#

# Error during argument processing?
argError=0

# Need help?
showHelp=0

# Options to pass to `set-up-out`.
outOpts=()

# JSON text for the base contents of `package.json`, if any.
packageBaseJson='{}'

# Path to the product info file.
productInfoPath="${baseDir}/product-info.txt"

# Publish?
publish=0

# Extra options to pass to `npm publish`.
publishOpts=()

# List of rescopings to do.
rescopes=()

while true; do
    case $1 in
        -h|--help)
            showHelp=1
            break
            ;;
        --dry-run|--verbose)
            publishOpts+=("$1")
            ;;
        --out=?*)
            outOpts+=("$1")
            ;;
        --package-base=?*)
            packageBaseJson="${1#*=}"
            ;;
        --product-info=?*)
            productInfoPath="${1#*=}"
            ;;
        --public)
            publishOpts+=('--access=public')
            ;;
        --publish)
            publish=1
            ;;
        --rescope=?*)
            rescopes+=("${1#*=}")
            ;;
        --) # End of all options
            shift
            break
            ;;
        -?*)
            echo "Unknown option: $1" 1>&2
            argError=1
            break
            ;;
        *)  # Default case: No more options, break out of the loop.
            break
    esac

    shift
done

if [[ ${productInfoPath} == '' ]]; then
    echo 'Missing required option: --product-info' 1>&2
    argError=1
fi

if (( ${showHelp} || ${argError} )); then
    echo 'Usage:'
    echo ''
    echo "${progName} [<opt> ...]"
    echo '  Convert modules into publication form, and optionally publish them.'
    echo ''
    echo '  --dry-run'
    echo '    Passed through to `npm publish` when using `--publish`.'
    echo '  --out=<dir>'
    echo '    Directory where built output goes and also where the module sources are'
    echo '    found.'
    echo '  --package-base=<json>'
    echo '    JSON object for the base contents of `package.json`. If not specified,'
    echo '    minimal defaults will be used.'
    echo '  --product-info=<path>'
    echo '    Filesystem path to the product info file.'
    echo '  --public'
    echo '    With `--publish`, causes the published modules to be marked as public.'
    echo '  --publish'
    echo '    Actually publish the converted modules, using `npm publish`.'
    echo '  --rescope=@<original>:@<new>[/<prefix>]'
    echo '    Translate the indicated module scope in the originals into a new scope'
    echo '    name and optional module name prefix in the result. Can be specified'
    echo '    more than once.'
    echo '  --verbose'
    echo '    Passed through to `npm publish` when using `--publish`.'
    echo ''
    echo "${progName} [--help | -h]"
    echo '  Display this message.'
    exit ${argError}
fi


#
# Helper functions
#

# Helper for `make-name-map` which produces the translation for one module, if
# it is in fact rescoped.
function calc-name-map-entry {
    local fullName="$1"
    local scope name

    if [[ ${fullName} =~ ^(@[^/:]+)/(.*)$ ]]; then
        scope="${BASH_REMATCH[1]}"
        name="${BASH_REMATCH[2]}"
    else
        # No namespace scope in the given name. Rescopes only affect modules
        # that started out with a namespace.
        return
    fi

    local s
    for s in "${rescopes[@]}"; do
        if [[ "${s}" =~ ^(@[^:/]+):(@[^/]+)(/[^/]+)?$ ]]; then
            local fromScope="${BASH_REMATCH[1]}"
            local toScope="${BASH_REMATCH[2]}"
            local toPrefix="${BASH_REMATCH[3]}"
            if [[ ${scope} == ${fromScope} ]]; then
                if [[ ${toPrefix} == '' ]]; then
                    toPrefix='/'
                fi
                echo "${toScope}${toPrefix}${name}"
                return
            fi
        else
            echo "Invalid rescope: ${s}" 1>&2
            return 1
        fi
    done

    # No match from any rescope spec.
}

# Builds up an array that maps the names of all of the existing local modules to
# their possibly-rescoped versions. Stores the results `nameMap[@]`
# (script-friendly array), `nameMapJson` (JSON object in string form), and
# `nameMapProgram[@]` (`jq` invocation which transforms source text).
#
# The `nameMapProgram` uses `jq` as a "sed but with better regex
# semantics." **Note #1**: `jq` uses the PCRE library. **Note #2:**
# Unfortunately, backslashes need to be doubled because `jq` doesn't have syntax
# for regex literals.
function make-name-map {
    nameMap=()
    nameMapJson=$'{\n'
    local jqProgram='.'
    local any=0

    # This validates all the rescope specs.
    calc-name-map-entry '@-/-' >/dev/null || return 1

    for name in $(local-module-names); do
        local result="$(calc-name-map-entry "${name}")"
        if [[ ${result} != '' ]]; then
            nameMap+=("${name}:${result}")

            nameMapJson+="  \"${name}\": \"${result}\","
            nameMapJson+=$'\n'

            local mapFrom='(?<!\\w)'"${name}"'\\b' # Require word-ish boundaries.
            jqProgram+=" | gsub(\"${mapFrom}\"; \"${result}\")"
        fi
        any=1
    done

    if (( !${any} )); then
        echo 'No modules found!' 1>&2
        return 1
    fi

    # The extra mapping is a hack to make it okay to spit out a comma for all
    # of the above mappings.
    nameMapJson+=$'  "": ""\n}\n'

    nameMapProgram=(jq --raw-input --raw-output --slurp "${jqProgram}")
}

# Determines the output module name for the given input module name.
function output-name-for {
    local name="$1"

    for entry in "${nameMap[@]}"; do
        [[ ${entry} =~ ^([^:]+):(.*)$ ]]
        local fromName="${BASH_REMATCH[1]}"
        local toName="${BASH_REMATCH[2]}"
        if [[ ${name} == ${fromName} ]]; then
            echo "${toName}"
            return
        fi
    done

    # No match from any rescope spec.
    echo "${name}"
}

# Processes the named module, producing a version suitable for publication.
function process-module {
    local name="$1"
    local toName="$(output-name-for "${name}")"
    local fromDir="${modulesDir}/${name}"
    local toDir="${publishDir}/${toName}"

    if [[ ${toName} == '' ]]; then
        return 1
    fi

    mkdir -p "${toDir}" || return 1

    # Start with a fresh copy of the module source. **Note:** `source-map.txt`
    # files are from the build process and are used for the "live development"
    # system; they shouldn't end up getting published, so we exclude them from
    # the copy.
    rsync-archive --delete --exclude=source-map.txt \
        "${fromDir}/" "${toDir}" \
    || return 1

    # Rework the `package.json` file.
    jq \
        --arg name "${toName}" \
        --arg version "${productVersion}" \
        --argjson nameMap "${nameMapJson}" \
        --argjson packageBase "${packageBaseJson}" \
    '
        def fix_name(name):
            name as $name |
            if $nameMap | has($name)
                then $nameMap[$name]
                else $name
            end
        ;

        def fix_dep:
            if (.value == "local")
                then .value = $version | .key = fix_name(.key)
                else .
            end
        ;

        {
            "description": "Subcomponent of the Bayou project.",
            "license":     "Apache-2.0",
            "author":      "See AUTHORS.md in repository.",
            "repository":  "https://github.com/danfuzz/bayou"
        }
        + $packageBase + . +
        {
            "name":    $name,
            "version": $version
        }

        |

        if has("dependencies")
            then .dependencies |= with_entries(fix_dep)
            else .
        end
    ' < "${fromDir}/package.json" > "${toDir}/package.json" \
    || return 1

    if [[ ${#nameMap[@]} == 0 ]]; then
        # No module name mappings, so nothing more to do.
        return
    fi

    # Because there are module name mappings, go through each source file and
    # perform replacements.

    local fileName
    (cd "${fromDir}"; find . -type f \
        '(' -name '*.js' -o -name '*.less' -o -name '*.md' ')') |
    while read -r fileName; do
        local fromFile="${fromDir}/${fileName}"
        local toFile="${toDir}/${fileName}"

        "${nameMapProgram[@]}" < "${fromFile}" > "${toFile}"
    done
}

# Determines the product version from the info file.
function product-version {
    if [[ ! (-r ${productInfoPath} && -f ${productInfoPath}) ]]; then
        echo "Not readable: ${productInfoPath}" 1>&2
        return 1
    fi

    local line="$(grep '^ *version *=' < "${productInfoPath}")"

    if [[ ${line} =~ ^\ *version\ *=\ *([^\ ]*) ]]; then
        echo "${BASH_REMATCH[1]}"
    else
        echo "Could not determine product version." 1>&2
        return 1
    fi
}

# Publishes all of the constructed modules.
function publish-modules {
    echo 'Publishing modules...'

    local publishCount=0
    local errors=()
    local plural

    for name in $(publishable-module-names); do
        echo "${name}"

        (
            cd "${publishDir}/${name}"
            npm publish "${publishOpts[@]}"
        )

        if [[ $? == 0 ]]; then
            ((publishCount++))
        else
            errors+=("${name}")
        fi
    done

    plural=''
    if (( ${publishCount} == 1 )); then
        plural='s'
    fi
    echo ''
    echo "Published ${publishCount} module${plural}."

    if (( ${#errors[@]} != 0 )); then
        echo '' 1>&2
        echo 'Trouble publishing the following:' 1>&2

        for name in "${errors[@]}"; do
            echo "  ${name}"
        done

        plural='s'
        if (( ${#errors[@]} == 1 )); then
            plural=''
        fi

        echo "${#errors[@]} error${plural}." 1>&2
        return 1
    fi
}

#
# Main script
#

set-up-out "${outOpts[@]}" || exit 1
make-name-map || exit 1

# Validate the base JSON.
if [[ ${packageBaseJson} != '' ]]; then
    # The `jq` command validates and canonicalizes the JSON contents.
    packageBaseJson="$(echo "${packageBaseJson}" | jq --compact-output .)"
    if [[ $? != 0 ]]; then
        echo 'Invalid JSON given for --package-base.' 1>&2
        exit 1
    fi

    if [[ ! ${packageBaseJson} =~ ^'{' ]]; then
        echo 'Non-object given for --package-base.' 1>&2
        exit 1
    fi
fi

productVersion="$(product-version)"
if [[ $? != 0 ]]; then
    exit 1
fi

publishDir="$(publish-dir)"
mkdir -p "${publishDir}" || exit 1

echo "Processing modules for publication..."

for name in $(local-module-names); do
    echo "${name}"
    process-module "${name}" || exit 1
done

if (( ${publish} )); then
    publish-modules || exit 1
    echo "Done!"
else
    echo "Done! Built modules into:"
    echo "  ${publishDir}"
fi
