#!/bin/bash
#
# Copyright 2016-2019 the Bayou Authors (Dan Bornstein et alia).
# Licensed AS IS and WITHOUT WARRANTY under the Apache License,
# Version 2.0. Details: <http://www.apache.org/licenses/LICENSE-2.0>
#
# Cleans the built product directory. See `--help` for details.
#

# Set `progName` to the program name, `progDir` to its directory, and `baseDir`
# to `progDir`'s directory. Follows symlinks.
function init-prog {
    local newp p="$0"

    while newp="$(readlink "$p")"; do
        [[ ${newp} =~ ^/ ]] && p="${newp}" || p="$(dirname "$p")/${newp}"
    done

    progName="${p##*/}"
    progDir="$(cd "$(dirname "$p")"; /bin/pwd -P)"
    baseDir="$(cd "${progDir}/.."; /bin/pwd -P)"
}
init-prog


#
# Argument parsing
#

# Error during argument processing?
argError=0

# Need help?
showHelp=0

# Create directory?
create=0

# Output directory.
outDir=''

while true; do
    case $1 in
        -h|--help)
            showHelp=1
            break
            ;;
        --create)
            create=1
            ;;
        --out=?*)
            outDir="${1#*=}"
            ;;
        --) # End of all options
            shift
            break
            ;;
        -?*)
            echo "Unknown option: $1" 1>&2
            argError=1
            break
            ;;
        *)  # Default case: No more options, break out of the loop.
            break
    esac

    shift
done

if (( ${showHelp} || ${argError} )); then
    echo 'Usage:'
    echo ''
    echo "${progName} [<opt> ...]"
    echo '  Clean the project output.'
    echo ''
    echo '  --create'
    echo '    Create the directory (leaving it empty). Without this option,'
    echo '    this script just removes the directory if it exists.'
    echo '  --out=<dir>'
    echo '    Directory where built output goes.'
    echo ''
    echo "${progName} [--help | -h]"
    echo '  Display this message.'
    exit ${argError}
fi


#
# Main script
#

# Options to pass to `out-dir-setup`.
setupOpts=()

if [[ ${outDir} != '' ]]; then
    setupOpts+=("--out=${outDir}")
fi

if (( ${create} )); then
    setupOpts+=('--clean')
else
    setupOpts+=('--just-clean')
fi

"${progDir}/lib/out-dir-setup" --no-print "${setupOpts[@]}"
