#!/bin/bash
#
# Copyright 2016-2017 the Bayou Authors (Dan Bornstein et alia).
# Licensed AS IS and WITHOUT WARRANTY under the Apache License,
# Version 2.0. Details: <http://www.apache.org/licenses/LICENSE-2.0>
#
# Runs all the tests.
#

# Set `progName` to the program name, `progDir` to its directory, and `baseDir`
# to `progDir`'s directory. Follows symlinks.
function init-prog {
    local newp p="$0"

    while newp="$(readlink "$p")"; do
        [[ ${newp} =~ ^/ ]] && p="${newp}" || p="$(dirname "$p")/${newp}"
    done

    progName="${p##*/}"
    progDir="$(cd "$(dirname "$p")"; /bin/pwd -P)"
    baseDir="$(cd "${progDir}/.."; /bin/pwd -P)"
}
init-prog


#
# Argument parsing
#

# Error during argument processing?
argError=0

# Need help?
showHelp=0

# Output directory option, if any.
outDirOpt=()

while (( $# != 0 )); do
    opt="$1"
    if [[ ${opt} == '--' ]]; then
        shift
        break
    elif [[ ${opt} == '--create' ]]; then
        create=1
    elif [[    ${opt} == '--help'
            || ${opt} == '-h' ]]; then
        showHelp=1
    elif [[ ${opt} =~ ^--out= ]]; then
        outDirOpt="${opt}"
    elif [[ ${opt} =~ ^- ]]; then
        echo "Unknown option: ${opt}" 1>&2
        argError=1
        break
    else
        break
    fi
    shift
done
unset opt

if (( ${showHelp} || ${argError} )); then
    echo 'Usage:'
    echo ''
    echo "${progName} [--out=<dir>]"
    echo '  Runs the project tests.'
    echo ''
    echo '  --out=<dir>'
    echo '    Directory containing the built output, and where test results are'
    echo '    stored.'
    echo ''
    echo "${progName} [--help | -h]"
    echo '  Display this message.'
    exit ${argError}
fi


#
# Main script
#

outDir="$(${progDir}/lib/out-dir-setup "${outDirOpt[@]}")"
if (( $? != 0 )); then
    return 1
fi

runProduct="${outDir}/final/bin/run"
testOutDir="${outDir}/test-results"
error=0

if [[ ! -e ${runProduct} ]]; then
    echo 'Could not find `run` script. Did you forget to build?' 1>&2
    exit 1
fi

mkdir -p "${testOutDir}"

"${runProduct}" --client-bundle | tee "${testOutDir}/client-bundle.txt"
if (( $? != 0 )); then
    error=1
fi

"${runProduct}" --server-test | tee "${testOutDir}/server-test.txt"
if (( $? != 0 )); then
    error=1
fi

exit "${error}"
